[package]
name = "rpc-codec-msgpack"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
rpc-core.workspace = true
serde.workspace = true
rmp-serde.workspace = true
