[package]
name = "rpc-openapi"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json.workspace = true
schema.workspace = true
schema-openapi.workspace = true
