[package]
name = "rpc-codec-json"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
rpc-core.workspace = true
serde.workspace = true
serde_json.workspace = true
